<!DOCTYPE html>
<html class="writer-html5" lang="en" >
<head>
  <meta charset="utf-8" /><meta name="generator" content="Docutils 0.17.1: http://docutils.sourceforge.net/" />

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>1.6. Understanding Errors and Catching Exceptions &mdash; Computer Science with Applications  documentation</title>
      <link rel="stylesheet" href="../../_static/pygments.css" type="text/css" />
      <link rel="stylesheet" href="../../_static/css/theme.css" type="text/css" />
      <link rel="stylesheet" href="../../_static/csapps.css" type="text/css" />
  <!--[if lt IE 9]>
    <script src="../../_static/js/html5shiv.min.js"></script>
  <![endif]-->
  
        <script data-url_root="../../" id="documentation_options" src="../../_static/documentation_options.js"></script>
        <script src="../../_static/jquery.js"></script>
        <script src="../../_static/underscore.js"></script>
        <script src="../../_static/_sphinx_javascript_frameworks_compat.js"></script>
        <script src="../../_static/doctools.js"></script>
    <script src="../../_static/js/theme.js"></script>
    <link rel="index" title="Index" href="../../genindex.html" />
    <link rel="search" title="Search" href="../../search.html" />
    <link rel="next" title="1.7. Example: A Game of Chance" href="../example/index.html" />
    <link rel="prev" title="1.5. Basics of Code Organization" href="../organization/index.html" /> 
</head>

<body class="wy-body-for-nav"> 
  <div class="wy-grid-for-nav">
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search" >
            <a href="../../index.html" class="icon icon-home"> Computer Science with Applications
          </a>
<div role="search">
  <form id="rtd-search-form" class="wy-form" action="../../search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>
        </div><div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="Navigation menu">
              <ul>
<li class="toctree-l1"><a class="reference internal" href="../../preface.html">Preface</a></li>
</ul>
<ul class="current">
<li class="toctree-l1 current"><a class="reference internal" href="../index.html">1. Getting Started</a><ul class="current">
<li class="toctree-l2"><a class="reference internal" href="../introduction/index.html">1.1. Computational Thinking</a></li>
<li class="toctree-l2"><a class="reference internal" href="../basics/index.html">1.2. Programming Basics</a></li>
<li class="toctree-l2"><a class="reference internal" href="../control_structures/index.html">1.3. Control Flow Statements</a></li>
<li class="toctree-l2"><a class="reference internal" href="../intro_functions/index.html">1.4. Introduction to Functions</a></li>
<li class="toctree-l2"><a class="reference internal" href="../organization/index.html">1.5. Basics of Code Organization</a></li>
<li class="toctree-l2 current"><a class="current reference internal" href="#">1.6. Understanding Errors and Catching Exceptions</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#catching-exceptions">1.6.1. Catching exceptions</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="../example/index.html">1.7. Example: A Game of Chance</a></li>
</ul>
</li>
<li class="toctree-l1"><a class="reference internal" href="../../data_structures/index.html">2. Data Structures</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../functions/index.html">3. Functional Programming and Recursion</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../working_with_data/index.html">4. Working with Data</a></li>
</ul>

        </div>
      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap"><nav class="wy-nav-top" aria-label="Mobile navigation menu" >
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="../../index.html">Computer Science with Applications</a>
      </nav>

      <div class="wy-nav-content">
        <div class="rst-content">
          <div role="navigation" aria-label="Page navigation">
  <ul class="wy-breadcrumbs">
      <li><a href="../../index.html" class="icon icon-home"></a> &raquo;</li>
          <li><a href="../index.html"><span class="section-number">1. </span>Getting Started</a> &raquo;</li>
      <li><span class="section-number">1.6. </span>Understanding Errors and Catching Exceptions</li>
      <li class="wy-breadcrumbs-aside">
            <a href="../../_sources/getting_started/exceptions/index.rst.txt" rel="nofollow"> View page source</a>
      </li>
  </ul>
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">
             
  <section id="understanding-errors-and-catching-exceptions">
<span id="chapter-exceptions"></span><h1><span class="section-number">1.6. </span>Understanding Errors and Catching Exceptions<a class="headerlink" href="#understanding-errors-and-catching-exceptions" title="Permalink to this heading"></a></h1>
<p>When Python detects something wrong in your code, it will <em>raise</em> an
<em>exception</em> to indicate that an error condition has occurred and it is
severe enough that Python can’t continue running the rest of your
code.</p>
<p>A very simple example of an exception occurs when we try to divide a
number by zero:</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="n">x</span> <span class="o">=</span> <span class="mi">42</span> <span class="o">/</span> <span class="mi">0</span>
</pre></div>
</div>
<p>Trying to run the above code will result in an error like this:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">Traceback</span> <span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="s2">&quot;&lt;stdin&gt;&quot;</span><span class="p">,</span> <span class="n">line</span> <span class="mi">1</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
<span class="ne">ZeroDivisionError</span><span class="p">:</span> <span class="n">division</span> <span class="n">by</span> <span class="n">zero</span>
</pre></div>
</div>
<p>Let’s start with the last line: it tells us the name of the exception
(<code class="docutils literal notranslate"><span class="pre">ZeroDivisionError</span></code>) and a description of why the exception was
raised (<code class="docutils literal notranslate"><span class="pre">division</span> <span class="pre">by</span> <span class="pre">zero</span></code>).</p>
<p>The error message contains a <em>stack trace</em> or a synopsis of the state of
the call stack when the error is detected.</p>
<p>Specifically, in this example, the first two lines constitute the
stack trace.  Because we directly typed <code class="docutils literal notranslate"><span class="pre">x</span> <span class="pre">=</span> <span class="pre">42</span> <span class="pre">/</span> <span class="pre">0</span></code> into
the interpreter, these lines don’t provide a lot of information in
this case (it is immediately apparent that the error originated in the
code we just typed).</p>
<p>The stack trace is much more useful when an exception is raised inside
a function, as it will tell us the exact line inside that function
where the exception was raised. Not just that, it will provide us with
the complete sequence of function calls that led to the exception.</p>
<p>For example, suppose we wanted to write a simple program that prints
the result of dividing an integer N by all the positive integers less
than N.</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">divide</span><span class="p">(</span><span class="n">a</span><span class="p">,</span> <span class="n">b</span><span class="p">):</span>
<span class="w">    </span><span class="sd">&#39;&#39;&#39; divide a by b &#39;&#39;&#39;</span>
    <span class="k">return</span> <span class="n">a</span> <span class="o">/</span> <span class="n">b</span>

<span class="k">def</span> <span class="nf">print_divisions</span><span class="p">(</span><span class="n">N</span><span class="p">):</span>
<span class="w">    </span><span class="sd">&#39;&#39;&#39; Print result of dividing N by integers less than N. &#39;&#39;&#39;</span>
    <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="n">N</span><span class="p">):</span>
        <span class="n">d</span> <span class="o">=</span> <span class="n">divide</span><span class="p">(</span><span class="n">N</span><span class="p">,</span> <span class="n">i</span><span class="p">)</span>
        <span class="nb">print</span><span class="p">(</span><span class="n">N</span><span class="p">,</span> <span class="s2">&quot;/&quot;</span><span class="p">,</span> <span class="n">i</span><span class="p">,</span> <span class="s2">&quot;=&quot;</span><span class="p">,</span> <span class="n">d</span><span class="p">)</span>
</pre></div>
</div>
<p>If we store this code in a file named <code class="docutils literal notranslate"><span class="pre">exc.py</span></code>, import it into
python, and then call the <code class="docutils literal notranslate"><span class="pre">print_divisions</span></code> function, we’ll see
something like this:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="kn">import</span> <span class="nn">exc</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">exc</span><span class="o">.</span><span class="n">print_divisions</span><span class="p">(</span><span class="mi">12</span><span class="p">)</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">1</span>, in <span class="n">&lt;module&gt;</span>
  File <span class="nb">&quot;exc.py&quot;</span>, line <span class="m">8</span>, in <span class="n">print_divisions</span>
<span class="w">    </span><span class="n">d</span> <span class="o">=</span> <span class="n">divide</span><span class="p">(</span><span class="n">N</span><span class="p">,</span> <span class="n">i</span><span class="p">)</span>
  File <span class="nb">&quot;exc.py&quot;</span>, line <span class="m">3</span>, in <span class="n">divide</span>
<span class="w">    </span><span class="k">return</span> <span class="n">a</span> <span class="o">/</span> <span class="n">b</span>
<span class="gr">ZeroDivisionError</span>: <span class="n">division by zero</span>
</pre></div>
</div>
<p>Notice how this stack trace is much more informative. In particular,
it tells us than an exception happened after the following sequence of
events:</p>
<ul class="simple">
<li><p>Python ran <code class="docutils literal notranslate"><span class="pre">exc.print_divisions(12)</span></code> in the interpreter (shown in the stack trace as as <code class="docutils literal notranslate"><span class="pre">File</span> <span class="pre">&quot;&lt;stdin&gt;&quot;,</span> <span class="pre">line</span> <span class="pre">1,</span>&#160; <span class="pre">in</span> <span class="pre">&lt;module&gt;</span></code>).</p></li>
<li><p>During the call to <code class="docutils literal notranslate"><span class="pre">print_divisions</span></code>, Python ran the line
<code class="docutils literal notranslate"><span class="pre">d</span> <span class="pre">=</span> <span class="pre">divide(N,</span> <span class="pre">i)</span></code>, located in line 8 in the file <code class="docutils literal notranslate"><span class="pre">exc.py</span></code>.</p></li>
<li><p>During the call to <code class="docutils literal notranslate"><span class="pre">divide</span></code>, Python ran the line <code class="docutils literal notranslate"><span class="pre">return</span> <span class="pre">a</span> <span class="pre">/</span> <span class="pre">b</span></code>,
located in line 3 of <code class="docutils literal notranslate"><span class="pre">exc.py</span></code>. This last entry in the stack
trace produced a <code class="docutils literal notranslate"><span class="pre">ZeroDivisionError</span></code> exception.</p></li>
</ul>
<p>Notice that this is simply a printed version of the function call
stack, which we covered in section <a class="reference internal" href="../intro_functions/index.html#call-stack"><span class="std std-ref">The function call stack</span></a> of the previous
chapter.</p>
<p>There is clearly something wrong in our code, and the exception’s
stack trace can be very useful to figure out exactly what is wrong.
Frequently there is a difference between the line that raises the
exception, and the code where the error actually originates. For
example, in this case, they are not the same! While it is true that
the <code class="docutils literal notranslate"><span class="pre">a</span> <span class="pre">/</span> <span class="pre">b</span></code> statement is the point at which the division by zero
occurs, there is actually nothing wrong with that particular line or
the <code class="docutils literal notranslate"><span class="pre">divide</span></code> function itself.  As a result, we turn our attention to
the next entry in the call stack:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">File</span> <span class="s2">&quot;exc.py&quot;</span><span class="p">,</span> <span class="n">line</span> <span class="mi">8</span><span class="p">,</span> <span class="ow">in</span> <span class="n">print_divisions</span>
   <span class="n">d</span> <span class="o">=</span> <span class="n">divide</span><span class="p">(</span><span class="n">N</span><span class="p">,</span> <span class="n">i</span><span class="p">)</span>
</pre></div>
</div>
<p>This line contains a hint at the source of the problem: <code class="docutils literal notranslate"><span class="pre">i</span></code> must
have taken on the value <code class="docutils literal notranslate"><span class="pre">0</span></code> at some point to have triggered the
<code class="docutils literal notranslate"><span class="pre">ZeroDivisionError</span></code> error.  Where does the <code class="docutils literal notranslate"><span class="pre">i</span></code> get its value?
From the <code class="docutils literal notranslate"><span class="pre">for</span></code> loop in <code class="docutils literal notranslate"><span class="pre">print_division</span></code>:</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="n">N</span><span class="p">):</span>
</pre></div>
</div>
<p>This <code class="docutils literal notranslate"><span class="pre">for</span></code> loop will iterate over the values 0, 1, 2, … N-1; we
want to avoid the value zero, so the <code class="docutils literal notranslate"><span class="pre">range</span></code> should start at one:</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="n">N</span><span class="p">):</span>
</pre></div>
</div>
<p>Instead of changing <code class="docutils literal notranslate"><span class="pre">exc.py</span></code>, we will copy the file to a new file
named <code class="docutils literal notranslate"><span class="pre">exc_fixed.py</span></code> and then fix the copy.  If import the corrected
version and run <code class="docutils literal notranslate"><span class="pre">exc_fixed.print_divisions(12)</span></code>, we will get:</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="kn">import</span> <span class="nn">exc_fixed</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">exc_fixed</span><span class="o">.</span><span class="n">print_divisions</span><span class="p">(</span><span class="mi">12</span><span class="p">)</span>
<span class="go">12 / 1 = 12.0</span>
<span class="go">12 / 2 = 6.0</span>
<span class="go">12 / 3 = 4.0</span>
<span class="go">12 / 4 = 3.0</span>
<span class="go">12 / 5 = 2.4</span>
<span class="go">12 / 6 = 2.0</span>
<span class="go">12 / 7 = 1.7142857142857142</span>
<span class="go">12 / 8 = 1.5</span>
<span class="go">12 / 9 = 1.3333333333333333</span>
<span class="go">12 / 10 = 1.2</span>
<span class="go">12 / 11 = 1.0909090909090908</span>
</pre></div>
</div>
<p>Now, we get the result we expect.  The loop starts at <code class="docutils literal notranslate"><span class="pre">1</span></code> and no
longer triggers the divide-by-zero exception.</p>
<p>So, when your code raises an exception, try not to fixate on the exact
line that raises the exception. While that line could be wrong, it is
just as likely that the actual origin of the exception is somewhere
else in your code.  The stack trace provides some hints as to where to
look for the error.  Systematically adding <code class="docutils literal notranslate"><span class="pre">print</span></code> statements that
highlight the value of crucial variables can help you isolate the
source of the error.</p>
<section id="catching-exceptions">
<h2><span class="section-number">1.6.1. </span>Catching exceptions<a class="headerlink" href="#catching-exceptions" title="Permalink to this heading"></a></h2>
<p>While exceptions can alert us to errors in our code, they can also be
<em>caught</em> and handled in a way that is consistent with the goals of the
application.  In the case of our <code class="docutils literal notranslate"><span class="pre">divide</span></code> function, we’ll just
return <code class="docutils literal notranslate"><span class="pre">None</span></code> to indicate to the client that the value of <code class="docutils literal notranslate"><span class="pre">a</span> <span class="pre">/</span> <span class="pre">b</span></code> is
not defined when <code class="docutils literal notranslate"><span class="pre">b</span></code> is zero.</p>
<p>We can catch an exception with a <code class="docutils literal notranslate"><span class="pre">try</span></code> statement, also known as a
<code class="docutils literal notranslate"><span class="pre">try</span></code> .. <code class="docutils literal notranslate"><span class="pre">except</span></code> block.  For example:</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">divide</span><span class="p">(</span><span class="n">a</span><span class="p">,</span> <span class="n">b</span><span class="p">):</span>
<span class="w">    </span><span class="sd">&#39;&#39;&#39; divide a by b &#39;&#39;&#39;</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="n">ret_val</span> <span class="o">=</span> <span class="n">a</span> <span class="o">/</span> <span class="n">b</span>
    <span class="k">except</span> <span class="ne">ZeroDivisionError</span><span class="p">:</span>
        <span class="c1"># Send None back to the caller to signal</span>
        <span class="c1"># that a / b is not defined.</span>
        <span class="n">ret_val</span> <span class="o">=</span> <span class="kc">None</span>
    <span class="k">return</span> <span class="n">ret_val</span>
</pre></div>
</div>
<p>We will store this version of <code class="docutils literal notranslate"><span class="pre">divide</span></code> along with the original code
for <code class="docutils literal notranslate"><span class="pre">print_divisions</span></code> (shown below) in a file named <code class="docutils literal notranslate"><span class="pre">exc_try.py</span></code>:</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">print_divisions</span><span class="p">(</span><span class="n">N</span><span class="p">):</span>
<span class="w">  </span><span class="sd">&#39;&#39;&#39; Print result of dividing N by integers less than N. &#39;&#39;&#39;</span>
  <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="n">N</span><span class="p">):</span>
      <span class="n">d</span> <span class="o">=</span> <span class="n">divide</span><span class="p">(</span><span class="n">N</span><span class="p">,</span> <span class="n">i</span><span class="p">)</span>
      <span class="nb">print</span><span class="p">(</span><span class="n">N</span><span class="p">,</span> <span class="s2">&quot;/&quot;</span><span class="p">,</span> <span class="n">i</span><span class="p">,</span> <span class="s2">&quot;=&quot;</span><span class="p">,</span> <span class="n">d</span><span class="p">)</span>
</pre></div>
</div>
<p>If we run this new version, we will get:</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="kn">import</span> <span class="nn">exc_try</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">exc_try</span><span class="o">.</span><span class="n">print_divisions</span><span class="p">(</span><span class="mi">12</span><span class="p">)</span>
<span class="go">12 / 0 = None</span>
<span class="go">12 / 1 = 12.0</span>
<span class="go">12 / 2 = 6.0</span>
<span class="go">12 / 3 = 4.0</span>
<span class="go">12 / 4 = 3.0</span>
<span class="go">12 / 5 = 2.4</span>
<span class="go">12 / 6 = 2.0</span>
<span class="go">12 / 7 = 1.7142857142857142</span>
<span class="go">12 / 8 = 1.5</span>
<span class="go">12 / 9 = 1.3333333333333333</span>
<span class="go">12 / 10 = 1.2</span>
<span class="go">12 / 11 = 1.0909090909090908</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">try</span></code> statement allows us to “try” a piece of code, which we write
after the <code class="docutils literal notranslate"><span class="pre">try</span></code> and, if it raises an exception, run an alternate
piece of code, which can be found after the <code class="docutils literal notranslate"><span class="pre">except</span></code>.  In this case,
the division in the first call to <code class="docutils literal notranslate"><span class="pre">divide</span></code> will trigger the
exception and the code in the <code class="docutils literal notranslate"><span class="pre">except</span></code> clause will be run and will
set <code class="docutils literal notranslate"><span class="pre">ret_val</span></code> to <code class="docutils literal notranslate"><span class="pre">None</span></code>.  Once the code in the <code class="docutils literal notranslate"><span class="pre">except</span></code> clause
is finished, the <code class="docutils literal notranslate"><span class="pre">return</span></code> statement that follows the <code class="docutils literal notranslate"><span class="pre">try</span></code>
statement will be executed.  The value of <code class="docutils literal notranslate"><span class="pre">ret_val</span></code> will be
returned to <code class="docutils literal notranslate"><span class="pre">print_divisions</span></code>, which, in turn, will simply print it
as the result of the division.  None of the subsequent calls to
<code class="docutils literal notranslate"><span class="pre">divide</span></code> in the loop will raise the exception.  In these cases,
<code class="docutils literal notranslate"><span class="pre">ret_val</span></code> will simply be set to the result of the division and
returned as expected.</p>
<p>The <code class="docutils literal notranslate"><span class="pre">divide</span></code> function as written now handles division by zero
without failing.  Notice, however, that it can still fail.  For
example, notice what happens if we pass it non-numeric arguments:</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="n">exc_try</span><span class="o">.</span><span class="n">divide</span><span class="p">(</span><span class="s2">&quot;abc&quot;</span><span class="p">,</span> <span class="s2">&quot;a&quot;</span><span class="p">)</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">1</span>, in <span class="n">&lt;module&gt;</span>
  File <span class="nb">&quot;exc.py&quot;</span>, line <span class="m">4</span>, in <span class="n">divide</span>
<span class="w">    </span><span class="k">return</span> <span class="n">a</span> <span class="o">/</span> <span class="n">b</span>
<span class="gr">TypeError</span>: <span class="n">unsupported operand type(s) for /: &#39;str&#39; and &#39;str&#39;</span>
</pre></div>
</div>
<p>This usage raises a different type of exception, a <code class="docutils literal notranslate"><span class="pre">TypeError</span></code>.  Our
<code class="docutils literal notranslate"><span class="pre">try</span></code> statement catches the <code class="docutils literal notranslate"><span class="pre">ZeroDivisionError</span></code> exception, but not
the <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> exception.  As a result, our program
stops, and the stack trace message shown above is printed,</p>
<p>Fortunately, we can catch multiple types of exceptions in the same
<code class="docutils literal notranslate"><span class="pre">try</span></code> statement:</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="kn">import</span> <span class="nn">sys</span>
<span class="k">def</span> <span class="nf">divide</span><span class="p">(</span><span class="n">a</span><span class="p">,</span> <span class="n">b</span><span class="p">):</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="n">ret_val</span> <span class="o">=</span> <span class="n">a</span> <span class="o">/</span> <span class="n">b</span>
    <span class="k">except</span> <span class="ne">ZeroDivisionError</span><span class="p">:</span>
        <span class="c1"># Send None back to the caller to signal</span>
        <span class="c1"># that a/b is not defined.</span>
        <span class="n">ret_val</span> <span class="o">=</span> <span class="kc">None</span>
    <span class="k">except</span> <span class="ne">TypeError</span> <span class="k">as</span> <span class="n">err</span><span class="p">:</span>
        <span class="c1"># Fail: no way to move forward.</span>
        <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Type error:, err)</span>
        <span class="n">sys</span><span class="o">.</span><span class="n">exit</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
    <span class="k">return</span> <span class="n">ret_val</span>
</pre></div>
</div>
<p>Now when we call <code class="docutils literal notranslate"><span class="pre">divide</span></code> on strings, our error message is printed
and the execution ends on the call to <code class="docutils literal notranslate"><span class="pre">sys.exit(1)</span></code>:</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="n">exc_try</span><span class="o">.</span><span class="n">divide</span><span class="p">(</span><span class="s2">&quot;abc&quot;</span><span class="p">,</span> <span class="s2">&quot;a&quot;</span><span class="p">)</span>
<span class="go">Type error: unsupported operand type(s) for /: &#39;str&#39; and &#39;str&#39;</span>
</pre></div>
</div>
<p>This example also illustrates another feature of exceptions: we can
use the keyword <code class="docutils literal notranslate"><span class="pre">as</span></code> to give a name to the exception that was
caught.  In this case, we use the name <code class="docutils literal notranslate"><span class="pre">err</span></code> and pass it to <code class="docutils literal notranslate"><span class="pre">print</span></code>
along with the string <code class="docutils literal notranslate"><span class="pre">&quot;Type</span> <span class="pre">error:&quot;</span></code>.  Using a mechanism that we’ll
discuss in the chapter on <a class="reference internal" href="../../data_structures/classes/index.html#chapter-classes"><span class="std std-ref">Classes and Objects</span></a>, <code class="docutils literal notranslate"><span class="pre">print</span></code> extracts a
string that describes the exception that occurred from <code class="docutils literal notranslate"><span class="pre">err</span></code> and prints
it.</p>
<p>We might not know all of the possible exceptions that can be raised by
a given piece of code when we first write it or the set of possible
exceptions might change over time (say, because a function we use has
changed and can now raise a broader set of exceptions).  If we want to
make sure to deal with all possible types of exceptions, we can catch
the generic exception <code class="docutils literal notranslate"><span class="pre">Exception</span></code>.  This exception is best used to
handle unexpected exceptions, as in:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="kn">import</span> <span class="nn">sys</span>
<span class="gp">&gt;&gt;&gt; </span><span class="k">def</span> <span class="nf">divide</span><span class="p">(</span><span class="n">a</span><span class="p">,</span> <span class="n">b</span><span class="p">):</span>
<span class="gp">... </span>    <span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>        <span class="n">ret_val</span> <span class="o">=</span> <span class="n">a</span> <span class="o">/</span> <span class="n">b</span>
<span class="gp">... </span>    <span class="k">except</span> <span class="ne">ZeroDivisionError</span><span class="p">:</span>
<span class="gp">... </span>        <span class="c1"># Send None back to the caller to signal</span>
<span class="gp">... </span>        <span class="c1"># that a/b is not defined.</span>
<span class="gp">... </span>        <span class="n">ret_val</span> <span class="o">=</span> <span class="kc">None</span>
<span class="gp">... </span>    <span class="k">except</span> <span class="ne">TypeError</span> <span class="k">as</span> <span class="n">err</span><span class="p">:</span>
<span class="gp">... </span>        <span class="c1"># Fail: no way to move forward.</span>
<span class="gp">... </span>        <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Type error:&quot;</span><span class="p">,</span> <span class="n">err</span><span class="p">)</span>
<span class="gp">... </span>        <span class="n">sys</span><span class="o">.</span><span class="n">exit</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
<span class="gp">... </span>    <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">err</span><span class="p">:</span>
<span class="gp">... </span>        <span class="c1"># Fail: no way to move forward.</span>
<span class="gp">... </span>        <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Unexpected error:&quot;</span><span class="p">,</span> <span class="n">err</span><span class="p">)</span>
<span class="gp">... </span>        <span class="n">sys</span><span class="o">.</span><span class="n">exit</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
<span class="gp">... </span>
<span class="gp">... </span>    <span class="k">return</span> <span class="n">ret_val</span>
<span class="gp">... </span>
</pre></div>
</div>
<p>The last <code class="docutils literal notranslate"><span class="pre">except</span></code> clause will only be executed, if the code in the
<code class="docutils literal notranslate"><span class="pre">try</span></code> block throws an exception other than <code class="docutils literal notranslate"><span class="pre">ZeroDivisionError</span></code> or
<code class="docutils literal notranslate"><span class="pre">TypeError</span></code>.  You might be tempted to use a generic <code class="docutils literal notranslate"><span class="pre">Exception</span></code> to
catch everything. Don’t.  It is likely that your application will be
better served by handling different exceptions in different ways.</p>
<p>The <code class="docutils literal notranslate"><span class="pre">try</span></code> statement also has an optional <code class="docutils literal notranslate"><span class="pre">finally</span></code> clause that
gets run whether an exception is raised or not. This clause is useful
when there are any cleanup operations that need to be performed
(closing files, closing database connections, etc.) regardless of
whether the code succeeded or failed.  For example:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="kn">import</span> <span class="nn">sys</span>
<span class="k">def</span> <span class="nf">divide</span><span class="p">(</span><span class="n">a</span><span class="p">,</span><span class="n">b</span><span class="p">):</span>
<span class="w">    </span><span class="sd">&#39;&#39;&#39; Divide a by b and catch exceptions&#39;&#39;&#39;</span>

    <span class="k">try</span><span class="p">:</span>
        <span class="n">ret_val</span> <span class="o">=</span> <span class="n">a</span> <span class="o">/</span> <span class="n">b</span>
    <span class="k">except</span> <span class="ne">ZeroDivisionError</span><span class="p">:</span>
        <span class="n">ret_val</span> <span class="o">=</span> <span class="kc">None</span>
    <span class="k">except</span> <span class="ne">TypeError</span> <span class="k">as</span> <span class="n">err</span><span class="p">:</span>
        <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Type error:&quot;</span><span class="p">,</span> <span class="n">err</span><span class="p">)</span>
        <span class="n">sys</span><span class="o">.</span><span class="n">exit</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
    <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">err</span><span class="p">:</span>
        <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Unexpected Error:&quot;</span><span class="p">,</span> <span class="n">err</span><span class="p">)</span>
        <span class="n">sys</span><span class="o">.</span><span class="n">exit</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
    <span class="k">finally</span><span class="p">:</span>
        <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;divide() was called with </span><span class="si">{}</span><span class="s2"> and </span><span class="si">{}</span><span class="s2">&quot;</span><span class="o">.</span><span class="n">format</span><span class="p">(</span><span class="n">a</span><span class="p">,</span> <span class="n">b</span><span class="p">))</span>

    <span class="k">return</span> <span class="n">ret_val</span>
</pre></div>
</div>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="n">divide</span><span class="p">(</span><span class="mi">6</span><span class="p">,</span> <span class="mi">2</span><span class="p">)</span>
<span class="go">divide() was called with 6 and 2</span>
<span class="go">3.0</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">divide</span><span class="p">(</span><span class="mi">6</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
<span class="go">divide() was called with 6 and 0</span>
</pre></div>
</div>
<p>Before we close this chapter, let’s look at what happens when we catch
some exceptions close to the source, but leave others to be handled
higher up the call stack.  Specifically, we’ll return to the example
from the start of the chapter.  We’ve modified <code class="docutils literal notranslate"><span class="pre">divide</span></code> to catch the
<code class="docutils literal notranslate"><span class="pre">TypeError</span></code>, but not <code class="docutils literal notranslate"><span class="pre">ZeroDivisionError</span></code>.  Instead, we’ll handle
that error in <code class="docutils literal notranslate"><span class="pre">print_divisions</span></code>.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="kn">import</span> <span class="nn">sys</span>
<span class="k">def</span> <span class="nf">divide</span><span class="p">(</span><span class="n">a</span><span class="p">,</span><span class="n">b</span><span class="p">):</span>
<span class="w">    </span><span class="sd">&#39;&#39;&#39; Divide a by b and catch exceptions&#39;&#39;&#39;</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="n">ret_val</span> <span class="o">=</span> <span class="n">a</span> <span class="o">/</span> <span class="n">b</span>
    <span class="k">except</span> <span class="ne">TypeError</span> <span class="k">as</span> <span class="n">err</span><span class="p">:</span>
        <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Type error:&quot;</span><span class="p">,</span> <span class="n">err</span><span class="p">)</span>
        <span class="n">sys</span><span class="o">.</span><span class="n">exit</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>

    <span class="k">return</span> <span class="n">ret_val</span>

<span class="k">def</span> <span class="nf">print_divisions</span><span class="p">(</span><span class="n">N</span><span class="p">):</span>
<span class="w">    </span><span class="sd">&#39;&#39;&#39; Print result of dividing N by integers less than N. &#39;&#39;&#39;</span>
    <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="n">N</span><span class="p">):</span>
        <span class="k">try</span><span class="p">:</span>
            <span class="n">d</span> <span class="o">=</span> <span class="n">divide</span><span class="p">(</span><span class="n">N</span><span class="p">,</span> <span class="n">i</span><span class="p">)</span>
            <span class="nb">print</span><span class="p">(</span><span class="n">N</span><span class="p">,</span> <span class="s2">&quot;/&quot;</span><span class="p">,</span> <span class="n">i</span><span class="p">,</span> <span class="s2">&quot;=&quot;</span><span class="p">,</span> <span class="n">d</span><span class="p">)</span>
        <span class="k">except</span> <span class="ne">ZeroDivisionError</span><span class="p">:</span>
            <span class="nb">print</span><span class="p">(</span><span class="n">N</span><span class="p">,</span> <span class="s2">&quot;/&quot;</span><span class="p">,</span> <span class="n">i</span><span class="p">,</span> <span class="s2">&quot;is undefined&quot;</span><span class="p">)</span>

<span class="n">print_divisions</span><span class="p">(</span><span class="mi">12</span><span class="p">)</span>
</pre></div>
</div>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>12 / 0 is undefined
12 / 1 = 12.0
12 / 2 = 6.0
12 / 3 = 4.0
12 / 4 = 3.0
12 / 5 = 2.4
12 / 6 = 2.0
12 / 7 = 1.7142857142857142
12 / 8 = 1.5
12 / 9 = 1.3333333333333333
12 / 10 = 1.2
12 / 11 = 1.0909090909090908
</pre></div>
</div>
<p>In the first iteration of the loop in <code class="docutils literal notranslate"><span class="pre">print_division</span></code>, <code class="docutils literal notranslate"><span class="pre">i</span></code> will
be zero, which will cause the division operation in <code class="docutils literal notranslate"><span class="pre">divide</span></code> to
raise an exception.  The <code class="docutils literal notranslate"><span class="pre">try</span></code> statement in <code class="docutils literal notranslate"><span class="pre">divide</span></code> catches type
errors, but not divide-by-zero errors.  So, Python will propagate the
error to call site in <code class="docutils literal notranslate"><span class="pre">print_division</span></code> to see if the call to
<code class="docutils literal notranslate"><span class="pre">divide</span></code> is nested within a <code class="docutils literal notranslate"><span class="pre">try</span></code> statement that knows how to
handle divide-by-zero errors.  In this case it is, and so, the
exception is handled by the <code class="docutils literal notranslate"><span class="pre">except</span></code> clause in <code class="docutils literal notranslate"><span class="pre">print_divisions</span></code>.
In general, an exception will be propagated up the call stack until it
is caught by an enclosing <code class="docutils literal notranslate"><span class="pre">try</span></code> statement or Python runs out of
functions on the stack.</p>
<p>We have only skimmed the surface of exceptions in this chapter.  You
now know enough to read error messages and handle simple exception
processing.  We’ll return to the topic of exceptions later in the book
to look ways to catch related types of errors in one <code class="docutils literal notranslate"><span class="pre">except</span></code> clause
and how to define and raise your own exceptions.</p>
</section>
</section>


           </div>
          </div>
          <footer><div class="rst-footer-buttons" role="navigation" aria-label="Footer">
        <a href="../organization/index.html" class="btn btn-neutral float-left" title="1.5. Basics of Code Organization" accesskey="p" rel="prev"><span class="fa fa-arrow-circle-left" aria-hidden="true"></span> Previous</a>
        <a href="../example/index.html" class="btn btn-neutral float-right" title="1.7. Example: A Game of Chance" accesskey="n" rel="next">Next <span class="fa fa-arrow-circle-right" aria-hidden="true"></span></a>
    </div>

  <hr/>

  <div role="contentinfo">
    <p>&#169; Copyright 2021, Anne Rogers and Borja Sotomayor.</p>
  </div>

  Built with <a href="https://www.sphinx-doc.org/">Sphinx</a> using a
    <a href="https://github.com/readthedocs/sphinx_rtd_theme">theme</a>
    provided by <a href="https://readthedocs.org">Read the Docs</a>.
   

</footer>
        </div>
      </div>
    </section>
  </div>
  <script>
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script> 

</body>
</html>